### ISSUE TITLE
Issues with the with the url the NSFW and Neko

### ISSUE THREAD

**Issue by werewolf26** [RatingGull27/KonataBot#35]
The NSFW url is not for now and the Neko to is not with the bot code
 so will be disable the All NSFW command and Neko command too

**Comment by werewolf26** [comment]
If anyone is having issues with our bot or the code when we are trying to fix the issues here is the list have issues
  NSFW commands  `not working`
lizard, cat commands `not working`
action commands  `not working`
Neko commands  `not working`
animu-picture commands `not working`

Look like the some the commands get the info is nekos.life and computerfreaker so yap

**Comment by werewolf26** [comment]
due to some of the code is not work when try to fix the issues but so look into the issues with the code

**Comment by Cozax** [comment]
Hey there. I would help but can you provide more informations about the problem?

**Comment by werewolf26** [comment]
Okay there the issues I'm have issues with node-fetch get the url with image
![fetchurl](https://user-images.githubusercontent.com/45981158/88439805-3d1b8600-cdda-11ea-8c20-62c327a3bc1b.png)
 It not post the image for url 
 
 here the code
![code issues](https://user-images.githubusercontent.com/45981158/88439904-72c06f00-cdda-11ea-9def-fdcce078b874.png)

**Comment by werewolf26** [comment]
Now change thing with the bot so In Progress now

- [ ] NSFW commands 
- [ ] cat commands
- [ ] action command
- [ ] Neko commands

**Comment by werewolf26** [comment]
This have fix issues on #71
